// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: changeset.proto

package changesetproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type GenerateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Oldtext string `protobuf:"bytes,1,opt,name=oldtext,proto3" json:"oldtext,omitempty"`
	Newtext string `protobuf:"bytes,2,opt,name=newtext,proto3" json:"newtext,omitempty"`
	Attribs string `protobuf:"bytes,3,opt,name=attribs,proto3" json:"attribs,omitempty"`
}

func (x *GenerateRequest) Reset() {
	*x = GenerateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_changeset_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRequest) ProtoMessage() {}

func (x *GenerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_changeset_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRequest.ProtoReflect.Descriptor instead.
func (*GenerateRequest) Descriptor() ([]byte, []int) {
	return file_changeset_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateRequest) GetOldtext() string {
	if x != nil {
		return x.Oldtext
	}
	return ""
}

func (x *GenerateRequest) GetNewtext() string {
	if x != nil {
		return x.Newtext
	}
	return ""
}

func (x *GenerateRequest) GetAttribs() string {
	if x != nil {
		return x.Attribs
	}
	return ""
}

// The response message containing the greetings
type GenerateReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Changeset string `protobuf:"bytes,1,opt,name=changeset,proto3" json:"changeset,omitempty"`
}

func (x *GenerateReply) Reset() {
	*x = GenerateReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_changeset_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateReply) ProtoMessage() {}

func (x *GenerateReply) ProtoReflect() protoreflect.Message {
	mi := &file_changeset_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateReply.ProtoReflect.Descriptor instead.
func (*GenerateReply) Descriptor() ([]byte, []int) {
	return file_changeset_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateReply) GetChangeset() string {
	if x != nil {
		return x.Changeset
	}
	return ""
}

var File_changeset_proto protoreflect.FileDescriptor

var file_changeset_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x08, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x73, 0x65, 0x74, 0x22, 0x5f, 0x0a, 0x0f, 0x47,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x6f, 0x6c, 0x64, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6f, 0x6c, 0x64, 0x74, 0x65, 0x78, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x65, 0x77, 0x74,
	0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x65, 0x77, 0x74, 0x65,
	0x78, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x73, 0x22, 0x2d, 0x0a, 0x0d,
	0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1c, 0x0a,
	0x09, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x65, 0x74, 0x32, 0x4d, 0x0a, 0x09, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x65, 0x74, 0x12, 0x40, 0x0a, 0x08, 0x47, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x12, 0x19, 0x2e, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x73, 0x65, 0x74, 0x2e,
	0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x17, 0x2e, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x73, 0x65, 0x74, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x11, 0x5a, 0x0f, 0x2f, 0x63,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x65, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_changeset_proto_rawDescOnce sync.Once
	file_changeset_proto_rawDescData = file_changeset_proto_rawDesc
)

func file_changeset_proto_rawDescGZIP() []byte {
	file_changeset_proto_rawDescOnce.Do(func() {
		file_changeset_proto_rawDescData = protoimpl.X.CompressGZIP(file_changeset_proto_rawDescData)
	})
	return file_changeset_proto_rawDescData
}

var file_changeset_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_changeset_proto_goTypes = []interface{}{
	(*GenerateRequest)(nil), // 0: changset.GenerateRequest
	(*GenerateReply)(nil),   // 1: changset.GenerateReply
}
var file_changeset_proto_depIdxs = []int32{
	0, // 0: changset.Changeset.Generate:input_type -> changset.GenerateRequest
	1, // 1: changset.Changeset.Generate:output_type -> changset.GenerateReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_changeset_proto_init() }
func file_changeset_proto_init() {
	if File_changeset_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_changeset_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_changeset_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_changeset_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_changeset_proto_goTypes,
		DependencyIndexes: file_changeset_proto_depIdxs,
		MessageInfos:      file_changeset_proto_msgTypes,
	}.Build()
	File_changeset_proto = out.File
	file_changeset_proto_rawDesc = nil
	file_changeset_proto_goTypes = nil
	file_changeset_proto_depIdxs = nil
}
